[env:esp32dev]
platform = espressif32 @ 6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200

; --- EGYEDI PARTÍCIÓS TÁBLA (OTA marad) ---
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L

; --- MÉRET OPTIMALIZÁLÁS ---
build_type = release

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DFW_VERSION=\"3.5\"
    -Wno-unused-variable

    ; size optim
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

    ; C++ size shrink
    -fno-exceptions
    -fno-rtti
    -DAUDIO_ENABLE_SD=0
    -DAUDIO_ENABLE_SDMMC=0
    -DAUDIO_ENABLE_SPIFFS=0
    -DAUDIO_ENABLE_FFAT=0
    -DAUDIO_GCC_OPTIMIZE=\"Os\"
build_unflags =
    -O2

; --- NE HÚZZUK BE A NEM HASZNÁLT TÁRHELYLIBEKET ---
; (Ha tényleg nincs SD kártya / FFat / SPIFFS használat a projektben, ezek menjenek.)


lib_deps =
    ;https://github.com/schreibfaul1/ESP32-audioI2S/archive/refs/tags/3.0.8.zip
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^7.0.0