[env:esp32s3]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- PSRAM (OSPI, 8MB) ---
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

; --- EGYEDI PARTÍCIÓS TÁBLA ---
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L

; --- MÉRET OPTIMALIZÁLÁS ---
build_type = release

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DFW_VERSION=\"S3.4\"
    -Wno-unused-variable

    ; ESP32-S3 specifikus
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

    ; size optim
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

    ; C++ size shrink
    -fno-exceptions
    -fno-rtti
    -DAUDIO_ENABLE_SD=0
    -DAUDIO_ENABLE_SDMMC=0
    -DAUDIO_ENABLE_SPIFFS=0
    -DAUDIO_ENABLE_FFAT=0
    -DAUDIO_GCC_OPTIMIZE=\"Os\"

build_unflags =
    -O2

; --- USB Serial (S3 beépített USB-CDC, nem UART0) ---
upload_protocol = esptool
monitor_filters = esp32_exception_decoder

lib_deps =
    ;https://github.com/schreibfaul1/ESP32-audioI2S/archive/refs/tags/3.0.8.zip
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^7.0.0